CREATE TABLE TB_ENDERECO OF TP_ENDERECO (
  CONSTRAINT CEP_PKEY PRIMARY KEY(CEP)
);

/

CREATE TABLE TB_TELEFONE_PESSOA OF TP_TELEFONE_PESSOA (
  CONSTRAINT TELEFONE_PESSOA_PKEY PRIMARY KEY(CPF_PESSOA)
);

/

CREATE TABLE TB_TELEFONE_FABRICA OF TP_TELEFONE_FABRICA (
  CONSTRAINT TEL_FAB_PKEY PRIMARY KEY(CNPJ_FABRICA)
);

CREATE TABLE TB_CLIENTE OF TP_CLIENTE (
  CONSTRAINT CLIENTE_PKEY PRIMARY KEY(ID_CLIENTE)
);

/

CREATE TABLE TB_FABRICA OF TP_FABRICA (
  CONSTRAINT FABRICA_PKEY PRIMARY KEY(CNPJ),
  ENDERECO SCOPE IS TB_ENDERECO
) NESTED TABLE FONE_FABRICA STORE AS ST_TELEFONE_FABRICA;

/

CREATE TABLE TB_FUNCIONARIO OF TP_FUNCIONARIO (
  CONSTRAINT FUNCIONARIO_PKEY PRIMARY KEY(MATRICULA),
  SUPERVISOR WITH ROWID REFERENCES TB_FUNCIONARIO
);

/

CREATE TABLE TB_MODELO_CARRO OF TP_MODELO_CARRO (
  CONSTRAINT MODELO_CARRO_PKEY PRIMARY KEY(MODELO)
);

/

CREATE TABLE TB_CARRO OF TP_CARRO (
  CONSTRAINT CARRO_PKEY PRIMARY KEY(CHASSI),
  MODELO WITH ROWID REFERENCES TB_MODELO_CARRO,
  CNPJ_FABRICA WITH ROWID REFERENCES TB_FABRICA
);

/

CREATE TABLE TB_VENDER_PROMO OF TP_VENDER_PROMO (
  CONSTRAINT VENDER_PROMO_PKEY PRIMARY KEY(CODIGO),
  CLIENTE WITH ROWID REFERENCES TB_CLIENTE,
  FUNCIONARIO WITH ROWID REFERENCES TB_FUNCIONARIO,
  CARRO WITH ROWID REFERENCES TB_CARRO
);